### ISSUE TITLE
[Feature-130] Improve NavBar CSS to support window scaling, add collapsable functionality

### ISSUE THREAD

**Issue by devAgant** [UTDallasEPICS/Wellness-Center-Older-Adults#130]
Improve the NavBar functionality on the dashboard to scale properly when exposed to different window sizes, and add the ability to collapse and hide the NavBar.

AC:

- A button to collapse the navigation bar and hide it
- A button to reopen the navigation bar

At large resolutions:
- The nav bar should push the page content to the right in order to take space

At small resolutions:
- The nav bar should float above the rest of the page content, without pushing the content to the right to take its own space.

**Comment by anishkothuri** [comment]
This issue is in Pull Request for Feature - 160
