### ISSUE TITLE
[Feature-166] Pull from Rides Database

### ISSUE THREAD

**Issue by AtreyaG** [UTDallasEPICS/Wellness-Center-Older-Adults#166]
Feature Description:
Pull existing rides from the database and display the pulled rides in the rides table

Requirements. 
Create a "GET" endpoint to pull ride(s) from the database
- replace the mock rides data json with real database data

**Comment by RVC13850** [comment]
I think the edit and delete button functionality is out of scope because when I pull from rides I am using IDs to make it easier and I have changed my schema to incorporate that. So i think we should not do it until we finalize the schema for the database.
