### ISSUE TITLE
[Feature-26] Dummy Dashboard

### ISSUE THREAD

**Issue by 4hmedSheik** [UTDallasEPICS/Wellness-Center-Older-Adults#26]
Feature Description
Creating a few boxes and other sections for the initial dashboard when users login.

Requirements
This dummy dashboard will be replicating the figma design and these will include the volunteer name when signed in, possibly show other statistics that would be useful to either the customer or volunteers.

**Comment by devAgant** [comment]
Best completed issue of the sprint, good work!
